{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "molecular.configSecretName" . }}
  labels:
    {{- include "molecular.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
{{- end }}